name: deploy
description: 'deploy to aws'

on:
  workflow_call:
    inputs:
      env-var:
        required: true
    secrets:
      token:
        required: true

jobs:
  check-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        env:
          ENV_VAR: ${{ inputs.env-var }}
          TOKEN: ${{ secrets.token }}
        run: echo %ENV_VAR% %TOKEN%
