name: deploy

on:
  workflow_call:
    inputs:
      env-var:
        required: true
        type: string
      MY_GET_REGISTRY_URL:
        type: string
        required: true
    secrets:
      token:
        required: true
      REPOSITORY_PAT:
        required: true
      MY_GET_REGISTRY_TOKEN:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env-vars
        run: |
          proto="$(echo ${{ inputs.MY_GET_REGISTRY_URL }} | grep :// | sed -e's,^\(.*://\).*,\1,g')"
          echo "MY_GET_NORMALIZED_REGISTRY_URL=$(echo ${{ inputs.MY_GET_REGISTRY_URL }} | sed -e s,$proto,,g)" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          node-version: "18.12.1"
          registry-url: ${{ inputs.MY_GET_REGISTRY_URL }}
      - name: Configure npm registry
        run: npm config set //${{ env.MY_GET_NORMALIZED_REGISTRY_URL }}:_authToken=${{ secrets.MY_GET_REGISTRY_TOKEN }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_PAT }}
          NPM_TOKEN: ${{ secrets.MY_GET_REGISTRY_TOKEN }}
        run: yarn semantic-release --branches="main"
