name: deploy

on:
  workflow_call:
    inputs:
      env-var:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  check-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: echo ${{ inputs.env-var }} ${{ secrets.token }}
