name: master

on:
  push:
    branches:
      - main
jobs:
  master-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Execute deploy action
        uses: ./.github/actions/deploy/
        with:
          env-var: ${{ vars.ENVIRONMENT_VARIABLE }}
          token: ${{ secrets.SECRET_TOKEN }}
