name: master

on:
  push:
    branches:
      - main
jobs:
  master-job:
    uses: ./.github/workflows/deploy.yml
    with:
      env-var: ${{ vars.ENVIRONMENT_VARIABLE }}
    secrets:
      token: ${{ secrets.SECRET_TOKEN }}
