name: master

on:
  push:
    branches:
      - main
jobs:
  master:
    uses: ./.github/workflows/deploy.yml
    with:
      env-var: ${{ vars.ENVIRONMENT_VARIABLE }}
      MY_GET_REGISTRY_URL: ${{ secrets.MY_GET_REGISTRY_URL }}
    secrets:
      token: ${{ secrets.SECRET_TOKEN }}
      REPOSITORY_PAT: ${{ secrets.REPOSITORY_PAT }}
      MY_GET_REGISTRY_TOKEN: ${{ secrets.MY_GET_REGISTRY_TOKEN }}
